# Welcome to Jekyll!

# Theme Settings
# theme: "minimal-mistakes-jekyll"
# remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # skins: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
title: "Cyber254"
title_separator: "-"
# subtitle: "Your tagline here"
name: "Vincent Olago"
description: "Welcome to my website."
url: "https://vinolago.github.io"
baseurl: "" # keep this empty for user/organization sites
# repository: "your-username/your-repo"
# teaser: "/assets/images/500x300.png"
# logo: "/assets/images/logo.png"
# masthead_title: "Cyber254"
# breadcrumbs: true
words_per_minute: 200
# enable_copy_code_button: true
# copyright: "Cyber254"
# copyright_url: "https://vinolago.github.io"

# Comments (optional)
comments:
  provider: false

# Atom Feed
atom_feed:
  path: # uses feed.xml by default

# Search
search: true
search_full_content: true
search_provider: lunr

# Social Sharing (Optional)
# twitter:
#   username: yourusername
# facebook:
#   username: yourusername
# og_image: /assets/images/site-preview.png

# Social Links (for SEO and cards)
social:
  type: Person
  name: "Vincent Olago"
  links:
    - "https://github.com/vinolago"
    - "https://linkedin.com/in/vincent-olago"
    - "https://tryhackme.com/p/vincentolagoo"
    - "https://app.hackthebox.com/profile/physcis"

# Site Author
author:
  name: "Vincent Olago"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "I am passionate about protecting systems and digital infrastructure and continuously sharpening my blue team skills."
  location: "Nairobi"
  email:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:dr.plancksolago@email.com"
    - label: "About"
      icon: "fas fa-fw fa-link"
      url: "https://vinolago.github.io/about"
    - label: "TryHackMe"
      icon: "fas fa-fw fa-link"
      url: "https://tryhackme.com/p/vincentolagoo"
    - label: "HackTheBox"
      icon: "fas fa-fw fa-link"
      url: "https://app.hackthebox.com/profile/physcis"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vinolago"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

# Header Navigation
header_pages:
  - _pages/resume.md
  - _pages/projects.md
  - _pages/contact.md

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/vinolago"
    - label: "TryHackMe"
      icon: "fas fa-fw fa-link"
      url: "https://tryhackme.com/p/vincentolagoo"
    - label: "HackTheBox"
      icon: "fas fa-fw fa-link"
      url: "https://app.hackthebox.com/profile/physcis"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# Reading and Build Settings
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Options
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:categories/:title/
timezone: Africa/Nairobi

# Pagination
paginate: 5
paginate_path: /page:num/

# Posts Pagination (Optional)
pagination:
  enabled: false
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  trail:
    before: 2
    after: 2

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
